-- USE ecm;
SHOW tables;
SELECT * FROM cart;
-- DESCRIBE user;
-- DESCRIBE address;
-- DESCRIBE user_address;
-- DESCRIBE user_roles;
-- DESCRIBE user_role_entity;
-- DESCRIBE products;
-- drop database ecm;